name: 'Tests'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["master", "maint/*"]
  pull_request:
    branches: ["master", "maint/*"]

permissions:
  contents: read

jobs:
  pytest:
    name: '${{ matrix.os }} / ${{ matrix.python }}'
    timeout-minutes: 70
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    env:
      MNE_HCP_N_RUNS: '3'
      SUBJECTS_DIR: '${{ github.workspace }}/subjects'
      MNE_LOGGING_LEVEL: warning
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: '3.8'  # TODO: Bump to 3.12
          # - os: macos-latest  # arm64 (Apple Silicon)
          #   python: '3.12'
          #   kind: mamba
          # - os: macos-13  # latest Intel release
          #   python: '3.12'
          #   kind: mamba
          # - os: windows-latest
          #   python: '3.12'
          # - os: ubuntu-20.04
          #   python: '3.8'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: pyvista/setup-headless-display-action@main
        with:
          qt: true
          pyvista: false
